---
# Source: monitoring-stack/templates/nginx-ingress-metrics/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-admission-nodeport
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - port: 10254
      targetPort: 10254
      protocol: TCP
      nodePort: 30100
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
