---
# Source: monitoring-stack/templates/nginx-ingress-metrics/service.yaml
# This YAML file defines a Kubernetes Service for the nginx-ingress controller.
# The Service is of type NodePort, which exposes the Service on each Node's IP at a static port (30100 in this case).
# The Service listens on port 10254 and forwards traffic to the same port on the target Pods.
# The selector ensures that the Service targets Pods with the labels app.kubernetes.io/name=ingress-nginx and app.kubernetes.io/component=controller.
# This setup is typically used to expose the nginx-ingress controller metrics endpoint externally.

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-admission-nodeport
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - port: 10254
      targetPort: 10254
      protocol: TCP
      nodePort: 30100
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
