# This configuration deploys Node Exporter as a DaemonSet and exposes it via a LoadBalancer service
# in the "monitoring" namespace.

# create the DaemonSet to install node-exporter to all node in the cluster
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter  # Name of the DaemonSet
  namespace: monitoring  # Namespace where the DaemonSet is deployed
spec:
  selector:
    matchLabels:
      app: node-exporter  # Match labels for the pods managed by this DaemonSet
  template:
    metadata:
      labels:
        app: node-exporter  # Labels for the pods to identify them
    spec:
      containers:
      - name: node-exporter  # Name of the container running Node Exporter
        image: prom/node-exporter:latest  # Docker image for Node Exporter
        ports:
        - containerPort: 9100  # Port on which the container listens for metrics
          name: metrics  # Name for the metrics port
