global:
  scrape_interval: 15s  # Set the scrape interval to 15 seconds

scrape_configs:
  - job_name: 'monitoring-stack-node-exporter'  # node metrics from Node Exporter on monitoring stack
    static_configs:
      - targets: 
        - '10.0.0.52:9100'  # Target local for Node Exporter to collect hardware and OS metrics on ev-grafana

  - job_name: 'prometheus-docker'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
        - 'localhost:9090'  # Target for Prometheus itself

  - job_name: 'dev-k3s-node-exporter'  # node level metrics from k3s cluster via node_exporter
    static_configs:
      - targets: 
        - '10.0.0.134:9100'
        - '10.0.0.137:9100'
        - '10.0.0.138:9100'
        - '10.0.0.140:9100'  
        - '10.0.0.141:9100'
        # Add targets for k3s cluster

  - job_name: 'dev-k3s-kube-state-metrics'  # get cluster level metric for kube-state-metrics from k3s cluster [use nodeport]
    static_configs:
      - targets: 
        - '10.0.0.134:30080'
        - '10.0.0.137:30080'
        - '10.0.0.138:30080'
        - '10.0.0.140:30080'
        - '10.0.0.141:30080'
        # Add more node IPs as needed

  - job_name: 'dev-k3s-cadvisor'  # get metrics from cAdvisor on K3s cluster
    static_configs:
      - targets: 
        - '10.0.0.134:30090'
        - '10.0.0.137:30090'
        - '10.0.0.138:30090'
        - '10.0.0.140:30090'
        - '10.0.0.141:30090'

  - job_name: 'dev-k3s-nginx-ingress-controller'  # get metrics from nginx-ingress-controller
    static_configs:
      - targets: 
        - '10.0.0.134:30100'
        - '10.0.0.137:30100'
        - '10.0.0.138:30100'
        - '10.0.0.140:30100'
        - '10.0.0.141:30100'

  - job_name: 'monitoring-stack-cadvisor'  # get metrics from cAdvisor (docker metrics)in monitoring stack
    static_configs:
      - targets:
        - 'localhost:8080'  # Target for cAdvisor

  - job_name: 'dev-k3s-redis-exporter'  # get metrics from redis-exporter on K3s cluster
    static_configs:
      - targets: 
        - '10.0.0.134:30110'
        - '10.0.0.137:30110'
        - '10.0.0.138:30110'
        - '10.0.0.140:30110'
        - '10.0.0.141:30110'