global:
  scrape_interval: 15s  # Set the scrape interval

scrape_configs:
  - job_name: 'monitoring-stack-node'
    static_configs:
      - targets: ['10.0.0.52:9100']  # Target local for Node Exporter to collect hardware and OS metrics

   - job_name: 'prometheus-docker'
     scheme: https
     tls_config:
       insecure_skip_verify: true
     static_configs:
       - targets: ['localhost:9090']  # Target for Prometheus itself

  - job_name: 'dev-k3s-cluster'  # node metrics from k3s cluster via node_exporter
    static_configs:
      - targets: 
        - '10.0.0.137:9100'
        - '10.0.0.138:9100'
        - '10.0.0.140:9100'  
        # Add targets for k8s cluster

  - job_name: 'dev-kube-state-metrics'  # get metric for kube-state-metrics from k3s cluster [use nodeport]
    static_configs:
      - targets: 
          - '10.0.0.137:30080'
          - '10.0.0.138:30080'
          - '10.0.0.140:30080'
          # Add more node IPs as needed

  - job_name: 'dev-cadvisor'  # get metrics from cAdvisor
    static_configs:
      - targets: 
          - '10.0.0.137:30090'
          - '10.0.0.138:30090'
          - '10.0.0.140:30090'

  - job_name: 'dev-nginx-ingress-controller'  # get metrics from nginx-ingress-controller
    static_configs:
      - targets: 
          - '10.0.0.137:30100'
          - '10.0.0.138:30100'
          - '10.0.0.140:30100'