apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          ports:
            - containerPort: 9121
          env:
            # Monitor both the master and the replica Redis services
            - name: REDIS_ADDR
              value: "redis-svc.ev.svc.cluster.local:6379,redis-follower-svc.ev.svc.cluster.local:6379" # Add both Redis service addresses here
            # No password required for Redis
            # - name: REDIS_PASSWORD
            #   value: "" # This can be omitted if not needed
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 5  # Adjust based on actual startup time
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 5  # Adjust based on actual startup time
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app: redis-exporter
spec:
  type: NodePort  # Change to ClusterIP if only for internal access
  ports:
    - name: metrics
      port: 9121
      targetPort: 9121
      nodePort: 30110  # Explicitly set the NodePort value
  selector:
    app: redis-exporter
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: monitoring
type: Opaque
data:
  password: ""  # Redis does not require a password, leave empty
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      interval: 30s  # Scrape interval for Prometheus