version: '3.7'

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    volumes:
      - grafana_data:/var/lib/grafana  # Persist Grafana data

volumes:
  grafana_data:  # Named volume for Grafana data