apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-admission-nodeport
  namespace: ingress-nginx
  annotations:
    meta.helm.sh/release-name: monitoring-stack
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 10254
      targetPort: 10254
      protocol: TCP
      nodePort: 30100  # External port
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller