version: '3.7'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"  # Map port 9090 on the host to port 9090 in the container
    volumes:
      - prometheus_data:/var/lib/prometheus  # Persist Prometheus data
      - /home/ec2-user/prometheus_ssl/prometheus.crt:/etc/prometheus/prometheus.crt  # Mount the SSL certificate
      - /home/ec2-user/prometheus_ssl/prometheus.key:/etc/prometheus/prometheus.key  # Mount the SSL key
      - /home/ec2-user/monitoring-stack/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus config
      - /home/ec2-user/monitoring-stack/prometheus/web-config.yml:/etc/prometheus/web-config.yml  # Mount web config

    environment:
      - PROMETHEUS_WEB_TLS_CERT_FILE=/etc/prometheus/prometheus.crt
      - PROMETHEUS_WEB_TLS_KEY_FILE=/etc/prometheus/prometheus.key

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'  # Specify the configuration file
      - '--storage.tsdb.retention.time=30d'  # Set retention time to 30 days
      - '--web.config.file=/etc/prometheus/web-config.yml'  # Specify the web config file

    deploy:
      resources:
        limits:
          memory: 1g  # Limit to 1GB of memory
          cpus: '1.0'  # Limit to 1 CPU core in total
        reservations:
          cpus: '0.5'  # Reserve 0.5 CPU cores

volumes:
  prometheus_data:
    name: monitoring-stack_prometheus_data
    external: true