apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics-loadbalancer
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-metrics
  selector:
    app: kube-state-metrics