apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-metrics
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - port: 10254
      targetPort: 10254
      protocol: TCP
      nodePort: 30054  # External port
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller