apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.14.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    nodePort: 30080  # You can specify a port or let Kubernetes assign one
  - name: telemetry
    port: 8081
    targetPort: telemetry
    nodePort: 30081  # You can specify a port or let Kubernetes assign one
  selector:
    app.kubernetes.io/name: kube-state-metrics
