apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: kube-system
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"cadvisor","namespace":"kube-system"},"spec":{"ports":[{"nodePort":30090,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"cadvisor"},"type":"NodePort"}}
spec:
  type: {{ .Values.cadvisor.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: {{ .Values.cadvisor.service.nodePort | default 30090 }}
  selector:
    app: cadvisor