apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginxIngressMetrics.service.name }}
  namespace: {{ .Values.nginxIngressMetrics.service.namespace }}
spec:
  type: {{ .Values.nginxIngressMetrics.service.type }}
  ports:
    - port: {{ .Values.nginxIngressMetrics.service.port }}
      targetPort: {{ .Values.nginxIngressMetrics.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.nginxIngressMetrics.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ .Values.nginxIngressMetrics.selector.name }}
    app.kubernetes.io/component: {{ .Values.nginxIngressMetrics.selector.component }}